# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .personalization_client import PersonalizationClient
from .version import VERSION

__all__ = ['PersonalizationClient']

__version__ = VERSION

