/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.personalizer.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A resulting ordered list of actions that result from a rank request.
 */
public class RankResponse {
    /**
     * The calculated ranking for the current request.
     */
    @JsonProperty(value = "ranking")
    private List<RankedAction> ranking;

    /**
     * The eventId for the round trip from request to response.
     */
    @JsonProperty(value = "eventId")
    private String eventId;

    /**
     * The action chosen by the Personalization service. This is the action for
     * which to report the reward. This might not be the
     * first found in 'ranking' if an action in the request in first position
     * was part of the excluded ids.
     */
    @JsonProperty(value = "rewardActionId")
    private String rewardActionId;

    /**
     * Get the calculated ranking for the current request.
     *
     * @return the ranking value
     */
    public List<RankedAction> ranking() {
        return this.ranking;
    }

    /**
     * Set the calculated ranking for the current request.
     *
     * @param ranking the ranking value to set
     * @return the RankResponse object itself.
     */
    public RankResponse withRanking(List<RankedAction> ranking) {
        this.ranking = ranking;
        return this;
    }

    /**
     * Get the eventId for the round trip from request to response.
     *
     * @return the eventId value
     */
    public String eventId() {
        return this.eventId;
    }

    /**
     * Set the eventId for the round trip from request to response.
     *
     * @param eventId the eventId value to set
     * @return the RankResponse object itself.
     */
    public RankResponse withEventId(String eventId) {
        this.eventId = eventId;
        return this;
    }

    /**
     * Get the action chosen by the Personalization service. This is the action for which to report the reward. This might not be the
     first found in 'ranking' if an action in the request in first position was part of the excluded ids.
     *
     * @return the rewardActionId value
     */
    public String rewardActionId() {
        return this.rewardActionId;
    }

    /**
     * Set the action chosen by the Personalization service. This is the action for which to report the reward. This might not be the
     first found in 'ranking' if an action in the request in first position was part of the excluded ids.
     *
     * @param rewardActionId the rewardActionId value to set
     * @return the RankResponse object itself.
     */
    public RankResponse withRewardActionId(String rewardActionId) {
        this.rewardActionId = rewardActionId;
        return this;
    }

}
