/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.personalizer.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A ranked action with its resulting probability.
 */
public class RankedAction {
    /**
     * Id of the action.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Probability of the action.
     */
    @JsonProperty(value = "probability")
    private Double probability;

    /**
     * Get id of the action.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set id of the action.
     *
     * @param id the id value to set
     * @return the RankedAction object itself.
     */
    public RankedAction withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get probability of the action.
     *
     * @return the probability value
     */
    public Double probability() {
        return this.probability;
    }

    /**
     * Set probability of the action.
     *
     * @param probability the probability value to set
     * @return the RankedAction object itself.
     */
    public RankedAction withProbability(Double probability) {
        this.probability = probability;
        return this;
    }

}
