/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.personalizer.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Reward given to a rank response.
 */
public class RewardRequest {
    /**
     * Reward to be assigned to an action. Value must be between -1 and 1
     * inclusive.
     */
    @JsonProperty(value = "value")
    private Double value;

    /**
     * Get reward to be assigned to an action. Value must be between -1 and 1 inclusive.
     *
     * @return the value value
     */
    public Double value() {
        return this.value;
    }

    /**
     * Set reward to be assigned to an action. Value must be between -1 and 1 inclusive.
     *
     * @param value the value value to set
     * @return the RewardRequest object itself.
     */
    public RewardRequest withValue(Double value) {
        this.value = value;
        return this;
    }

}
