# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ContainerStatus(Model):
    """ContainerStatus.

    :param service:
    :type service: str
    :param api_status:
    :type api_status: str
    :param api_status_message:
    :type api_status_message: str
    """

    _attribute_map = {
        'service': {'key': 'service', 'type': 'str'},
        'api_status': {'key': 'apiStatus', 'type': 'str'},
        'api_status_message': {'key': 'apiStatusMessage', 'type': 'str'},
    }

    def __init__(self, service=None, api_status=None, api_status_message=None):
        super(ContainerStatus, self).__init__()
        self.service = service
        self.api_status = api_status
        self.api_status_message = api_status_message
