# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RankableAction(Model):
    """An action with it's associated features used for ranking.

    :param id: Id of the action.
    :type id: str
    :param features: List of dictionaries containing features.
    :type features: list[object]
    """

    _validation = {
        'id': {'required': True},
        'features': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'features': {'key': 'features', 'type': '[object]'},
    }

    def __init__(self, id, features):
        super(RankableAction, self).__init__()
        self.id = id
        self.features = features
