# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RankResponse(Model):
    """A resulting ordered list of actions that result from a rank request.

    :param ranking: The calculated ranking for the current request.
    :type ranking: list[~swagger.models.RankedAction]
    :param event_id: The eventId for the round trip from request to response.
    :type event_id: str
    :param reward_action_id: The action chosen by the Personalization service.
     This is the action for which to report the reward. This might not be the
     first found in 'ranking' if an action in the request in first position was
     part of the excluded ids.
    :type reward_action_id: str
    """

    _attribute_map = {
        'ranking': {'key': 'ranking', 'type': '[RankedAction]'},
        'event_id': {'key': 'eventId', 'type': 'str'},
        'reward_action_id': {'key': 'rewardActionId', 'type': 'str'},
    }

    def __init__(self, ranking=None, event_id=None, reward_action_id=None):
        super(RankResponse, self).__init__()
        self.ranking = ranking
        self.event_id = event_id
        self.reward_action_id = reward_action_id
