# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RankedAction(Model):
    """A ranked action with its resulting probability.

    :param id: Id of the action
    :type id: str
    :param probability: Probability of the action
    :type probability: float
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'probability': {'key': 'probability', 'type': 'float'},
    }

    def __init__(self, id=None, probability=None):
        super(RankedAction, self).__init__()
        self.id = id
        self.probability = probability
