# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RewardRequest(Model):
    """Reward given to a rank response.

    :param value: Reward to be assigned to an action. Value must be between -1
     and 1 inclusive.
    :type value: float
    """

    _attribute_map = {
        'value': {'key': 'value', 'type': 'float'},
    }

    def __init__(self, value=None):
        super(RewardRequest, self).__init__()
        self.value = value
